version: '3'
services:
  roxwood_pwr:
    build: .
    environment:
      HOST: "flashfa_roxwood_pwr.digitarucamera.eu"
      DB_HOST: roxwood_pwr_db
      DB_USER: user
      DB_PASS: password
      DB_NAME: db
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.flashfaroxwood.loadbalancer.server.port=80
      - traefik.http.routers.flashfaroxwood-http.entrypoints=http
      - traefik.http.routers.flashfaroxwood-http.rule=Host(`flashfaroxwood.digitarucamera.eu`)
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.flashfaroxwood-http.middlewares=https-redirect@docker
      - traefik.http.routers.flashfaroxwood-https.entrypoints=https
      - traefik.http.routers.flashfaroxwood-https.rule=Host(`flashfaroxwood.digitarucamera.eu`)
      - traefik.http.routers.flashfaroxwood-https.tls=true
      - traefik.http.routers.flashfaroxwood-https.tls.certresolver=letsencrypt
    networks:
      - traefik

  roxwood_pwr_db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - traefik

  flashfaroxwoodpma:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: roxwood_pwr_db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.flashfaroxwoodpma-http.entrypoints=http
      - traefik.http.routers.flashfaroxwoodpma-http.rule=Host(`flashfaroxwoodpma.digitarucamera.eu`)
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.flashfaroxwoodpma-http.middlewares=https-redirect@docker
      - traefik.http.routers.flashfaroxwoodpma-https.entrypoints=https
      - traefik.http.routers.flashfaroxwoodpma-https.rule=Host(`flashfaroxwoodpma.digitarucamera.eu`)
      - traefik.http.routers.flashfaroxwoodpma-https.tls=true
      - traefik.http.routers.flashfaroxwoodpma-https.tls.certresolver=letsencrypt

networks:
  traefik:
    # external:
    #   name: web_traefik
